import { test, expect } from '@playwright/test'
import { mkdir } from 'node:fs/promises'
const screenshots = '../docs/screenshots'

test('calendar, free learning, review resume and mobile layout', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', e => errors.push(e.message))
  await mkdir(screenshots, { recursive: true })
  await page.setViewportSize({ width: 1440, height: 1100 })
  await page.goto('/')
  await expect(page.getByRole('heading', { name: '공부한 날이 쌓이는 곳' })).toBeVisible()
  await expect(page.getByText('20개 중 0개 복습 완료')).toBeVisible()
  await page.screenshot({ path: `${screenshots}/calendar-desktop.png`, fullPage: true })
  await page.setViewportSize({ width: 375, height: 812 })
  await page.screenshot({ path: `${screenshots}/calendar-mobile-initial.png`, fullPage: true })
  await page.setViewportSize({ width: 1440, height: 1100 })
  await page.getByRole('button', { name: '2026-09-03 학습 기록 있음', exact: true }).click()
  await expect(page.getByText('신규 20 · 복습 0')).toBeVisible()
  await page.getByRole('button', { name: '이전 달', exact: true }).click()
  await expect(page.getByRole('heading', { name: '2026년 8월' })).toBeVisible()
  await page.getByRole('button', { name: '다음 달', exact: true }).click()
  await expect(page.getByRole('heading', { name: '2026년 9월' })).toBeVisible()
  await page.getByRole('button', { name: '새 단어 배우기' }).click()
  await expect(page.getByText('interconnectedness', { exact: true })).toBeVisible()
  await page.setViewportSize({ width: 375, height: 812 })
  await page.getByRole('button', { name: '카드 뒤집기', exact: true }).click()
  await expect(page.getByText('서로 연결되어 있음; 상호 연결성')).toBeVisible()
  await page.screenshot({ path: `${screenshots}/card-mobile.png`, fullPage: true })
  await expect(page.locator('body')).toHaveJSProperty('scrollWidth', 375)
  await page.getByRole('button', { name: '알아요', exact: true }).click()
  await page.reload()
  await expect(page.getByText('thoughtful', { exact: true })).toBeVisible()
  async function answer(count: number) {
    for (let i = 0; i < count; i++) {
      await page.getByRole('button', { name: '카드 뒤집기', exact: true }).click()
      await page.getByRole('button', { name: i % 2 ? '몰라요' : '알아요', exact: true }).click()
    }
  }
  await answer(9)
  // Simulate an ambiguous response: the backend commits, the browser loses it.
  await page.route('**/v1/today/new', async route => { await route.fetch(); await route.abort('failed'); }, { times: 1 })
  await page.getByRole('button', { name: '학습 기록하기', exact: true }).click()
  await expect(page.getByRole('alert')).toBeVisible()
  await page.reload()
  await expect(page.getByRole('button', { name: '학습 기록하기', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '학습 기록하기', exact: true }).click()
  await expect(page.getByText('신규 10 · 복습 0')).toBeVisible()
  await expect(page.getByText('20개 중 0개 복습 완료')).toBeVisible()
  await page.getByRole('button', { name: '복습하기 →', exact: true }).click()
  await answer(10)
  await page.getByRole('button', { name: '학습 기록하기', exact: true }).click()
  await expect(page.getByText('신규 10 · 복습 10')).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: '복습 이어하기 →', exact: true }).click()
  await expect(page.getByText('bright', { exact: true })).toBeVisible()
  await answer(10)
  await page.getByRole('button', { name: '학습 기록하기', exact: true }).click()
  await expect(page.getByText('이날의 단어를 모두 복습했어요.')).toBeVisible()
  await page.getByRole('button', { name: '새 단어 배우기' }).click()
  await answer(5)
  await page.getByRole('button', { name: '학습 기록하기', exact: true }).click()
  await expect(page.getByText('신규 15 · 복습 20')).toBeVisible()
  await expect(page.getByRole('button', { name: '새 단어 배우기' })).toHaveCount(0)
  await page.screenshot({ path: `${screenshots}/calendar-mobile.png`, fullPage: true })
  await expect(page.locator('body')).toHaveJSProperty('scrollWidth', 375)
  await page.getByRole('link', { name: '진도', exact: true }).click()
  await expect(page.getByText('35', { exact: true })).toBeVisible()
  await expect(page.getByText('2일', { exact: true })).toBeVisible()
  expect(errors).toEqual([])
})
