import { test, expect } from '@playwright/test'
import { mkdir } from 'node:fs/promises'
const screenshots = '../docs/screenshots'

test('single-word learning, retry, review resume and mobile layout', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', e => errors.push(e.message))
  await mkdir(screenshots, { recursive: true })
  await page.setViewportSize({ width: 1440, height: 1100 })
  await page.goto('/')
  await expect(page.getByRole('heading', { name: '공부한 날이 쌓이는 곳' })).toBeVisible()
  await expect(page.getByText('20개 중 0개 복습 완료')).toBeVisible()
  await page.screenshot({ path: `${screenshots}/calendar-desktop.png`, fullPage: true })
  await page.setViewportSize({ width: 375, height: 812 })
  await page.screenshot({ path: `${screenshots}/calendar-mobile-initial.png`, fullPage: true })
  await page.setViewportSize({ width: 1440, height: 1100 })
  await page.getByRole('button', { name: '2026-09-03 학습 기록 있음', exact: true }).click()
  await expect(page.getByText('신규 20 · 복습 0')).toBeVisible()
  await page.getByRole('button', { name: '이전 달', exact: true }).click()
  await expect(page.getByRole('heading', { name: '2026년 8월' })).toBeVisible()
  await page.getByRole('button', { name: '다음 달', exact: true }).click()
  await expect(page.getByRole('heading', { name: '2026년 9월' })).toBeVisible()
  await page.getByRole('button', { name: '새 단어 배우기' }).click()
  await expect(page.getByText('interconnectedness', { exact: true })).toBeVisible()
  await page.setViewportSize({ width: 375, height: 812 })
  await page.getByRole('button', { name: '카드 뒤집기', exact: true }).click()
  await expect(page.getByText('서로 연결되어 있음; 상호 연결성')).toBeVisible()
  await page.screenshot({ path: `${screenshots}/card-mobile.png`, fullPage: true })
  await expect(page.locator('body')).toHaveJSProperty('scrollWidth', 375)
  await expect(page.getByRole('button', { name: '기억나요', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: '학습 완료', exact: true }).click()
  await expect(page.getByText('thoughtful', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByText('thoughtful', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '← 달력으로 돌아가기', exact: true }).click()
  await expect(page.getByText('신규 1 · 복습 0')).toBeVisible()
  await expect(page.getByText('신규 · 학습 완료', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '새 단어 배우기' }).click()
  async function answer(count: number, review = false) {
    for (let i = 0; i < count; i++) {
      await page.getByRole('button', { name: '카드 뒤집기', exact: true }).click()
      const response = page.waitForResponse(r => r.url().endsWith(`/v1/today/${review ? 'review' : 'new'}`) && r.request().method() === 'POST')
      await page.getByRole('button', { name: review ? (i % 2 ? '기억 안 나요' : '기억나요') : '학습 완료', exact: true }).click()
      expect((await response).status()).toBe(200)
      await expect(page.getByRole('button', { name: '저장하는 중…', exact: true })).toHaveCount(0)
    }
  }
  // Simulate an ambiguous response: the backend commits, the browser loses it.
  await page.route('**/v1/today/new', async route => { await route.fetch(); await route.abort('failed'); }, { times: 1 })
  await page.getByRole('button', { name: '카드 뒤집기', exact: true }).click()
  await page.getByRole('button', { name: '학습 완료', exact: true }).click()
  await expect(page.getByRole('alert')).toBeVisible()
  await expect(page.locator('.term', { hasText: 'thoughtful' })).toBeVisible()
  await expect(page.getByRole('button', { name: '← 달력으로 돌아가기', exact: true })).toBeDisabled()
  await page.reload()
  await page.getByRole('button', { name: '저장 다시 시도', exact: true }).click()
  await expect(page.getByText('curiosity', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '← 달력으로 돌아가기', exact: true }).click()
  await expect(page.getByText('신규 2 · 복습 0')).toBeVisible()
  await expect(page.getByText('20개 중 0개 복습 완료')).toBeVisible()
  await page.getByRole('button', { name: '복습하기 →', exact: true }).click()
  await answer(1, true)
  await page.getByRole('button', { name: '← 달력으로 돌아가기', exact: true }).click()
  await expect(page.getByText('신규 2 · 복습 1')).toBeVisible()
  await expect(page.getByText('복습 · 기억나요', { exact: true })).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: '복습 이어하기 →', exact: true }).click()
  await expect(page.getByText('wander', { exact: true })).toBeVisible()
  await answer(19, true)
  await expect(page.getByText('이날의 단어를 모두 복습했어요.')).toBeVisible()
  await page.getByRole('button', { name: '새 단어 배우기' }).click()
  await answer(13)
  await expect(page.getByText('신규 15 · 복습 20')).toBeVisible()
  await expect(page.getByRole('button', { name: '새 단어 배우기' })).toHaveCount(0)
  await page.screenshot({ path: `${screenshots}/calendar-mobile.png`, fullPage: true })
  await expect(page.locator('body')).toHaveJSProperty('scrollWidth', 375)
  await page.getByRole('link', { name: '진도', exact: true }).click()
  await expect(page.getByText('35', { exact: true })).toBeVisible()
  await expect(page.getByText('2일', { exact: true })).toBeVisible()
  expect(errors).toEqual([])
})
